Cargo.toml, src/imp/windows.rs
Switch to relying on `kernel32` for `ReOpenFile`.
As well `winapi` and `kernel32` are no-ops on non-windows platforms so just depend on them unconditionally.
=> Improve winapi usage

src/imp/unix.rs
Ran into this issue on arm. Unclear why they differ, but I'd imagine it's due to a mismatch between rustc's libc and the libc crate.
=> imp/unix: always cast cstr.as_ptr() to avoid issues with differing c_char types

Cargo.toml
This will allow non-Windows builds to avoid downloading the winapi crates.
=> Use target-specific dependencies

src/file/mod.rs
We missed this when going back-and-forth on the API design.
=> restore NamedTempFile::new_in

src/file/imp/unix.rs, tests/tempfile.rs
tmpfiles on unix systems without O_TMPFILE are not cleaned up after use. Fix this and add some tests to assert that tmpfile*() meets its guarantees with regard to security and resource leaking.
=> assert that tempfile*() meets its guarantees

src/dir.rs
Fixes #53 
We had some lingering references in the prose to some old method arguments on `TempDir`.
=> fix up some errors in docs

Cargo.toml, src/file/imp/mod.rs, src/file/imp/other.rs, src/lib.rs
This commit "adds support" for the wasm32-unknown-unknown target by simply
defining stubs that return errors, and it'll be up to crates depending on
`tempfile` to ensure they don't use this at runtime on wasm.
=> Fix compile on wasm32

src/dir.rs, src/error.rs, src/file/mod.rs, src/lib.rs, src/util.rs
Closes #71 
Adds an internal extension trait that lets us attach a `PathBuf` as context to an `io::Error` from temporary paths and directories when operations on them fail. It's not going to catch cases where we touch the underlying `File` itself, but should be a little more helpful for diagnostics.
cc @luser @Stebalien
=> Attach a path to errors where possible

src/error.rs
`std::io::Error` hasn't implemented `Error::source`, so we can't use that yet. Adding `#[allow(deprecated)]` is a temporary fix until `std::io::Error` is updated.
The warning/error that is fixed:
```
warning: use of deprecated item 'std::error::Error::cause': replaced by Error::source, which can support downcasting
--> src/error.rs:22:18
|
22 |         self.err.cause()
|                  ^^^^^
|
= note: #[warn(deprecated)] on by default
```
=> Fix nightly build

src/file/imp/unix.rs, src/file/imp/windows.rs, src/lib.rs, src/util.rs
This covers `&str`, `&OsStr`, etc. I'd rather take `AsRef<OsStr>` however, we'd then need to somehow own the content so we'd need to make the builder generic (and completely change the API).
fixes #58.
=> Change the builder to accept &AsRef<OsStr>

src/file/imp/unix.rs, src/file/mod.rs, tests/namedtempfile.rs
When looking into #40, I realized we weren't actually _doing_ what I claimed. Except for never-named tempfiles on Linux and auto-removed temporary files on Windows, we need to use absolute path names to guard against changes in the current working directory.
Unfortunately, this is a **[breaking change]** on some unix-like OSs. It's possible to:
1. Chdir to a directory.
2. Chmod the parent directory to remove the search (`x`) permission.
This will break any uses of absolute path names. The solution is the one described in #40: open the current directory, use `openat` on the relative path, and then close the current directory. However:
1. This will only help with unnamed temporary files unless we're willing to _hold_ the file directory open (probably not the best idea).
2. This will require …
=> Use absolute paths

src/file/imp/unix.rs
I removed the lfs feature without removing the cfg.
Based on #80.
=> Fix lfs support

.travis.yml, README.md, appveyor.yml, src/error.rs, src/file/mod.rs
This:
* Fixes some deprecation warnings.
* Removes the description function implementation.
* Replaces `cause` with `source` for improved downcasting.
=> feat: modernize errors and bump minimum version to 1.30

src/file/mod.rs
(mistakenly referred to new_in() instead)
=> Fix NamedTempFile::new() link

src/file/mod.rs
Addresses issue #110
Add a note that persist() does not quite match the atomic rename
pattern that is customary on Linux.
=> Clarify the behavior of persist

src/dir.rs
desctructor → destructor
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>
=> Fix two typos

src/file/mod.rs
The mem::replace idiom was unneeded, so replace it with more direct
code.
This fixes the lint issues breaking the build on master.
=> Use more direct code than mem::replace

Cargo.toml
The version was bumped for alexcrichton/cfg-if#37, which removed some inconsistent syntax which has no effect on this crate.  There are no other changes compared to the previous version.
=> Update to cfg-if 1.0

Cargo.toml
Closes #134
Updating remove_dir_all seems controversial (#123), so this only updates old dependencies other than remove_dir_all.
=> Update rand to 0.8, redox_syscall to 0.2

.travis.yml, Cargo.toml, src/file/imp/mod.rs, src/file/imp/unix.rs, src/lib.rs
WASI doesn't have a concept of system-wide temporary directory, but at least there is no reason why `new_in` methods with explicit paths should fail.
This PR implements support for such methods.
=> Add [limited] support for WASI

Cargo.toml, src/util.rs
#119 seems to have not been updated, so here's another take at it, trying to keep the diff as small as possible.
This approach stores a `SmallRng` as a thread-local variable, basically [directly copying the way `rand` does its own `thread_rng()`](https://github.com/rust-random/rand/blob/master/src/rngs/thread.rs) so as to avoid any issues or incompatibilities.
I opted not to further change the way that the `OsString` is built since that feels like it may be better in another PR.
=> use rand's SmallRng for random number generation

src/file/imp/unix.rs
Per #137 this PR remove the `O_EXCL` flag on Linux to enable Linux users to persist temp files without copying their contents.
```rust
// Note: Persisting tmp files will not work if the tmp directory and
// permanent directory are not on the same file system
let file = tmpfile::tmpfile_in(some_directory_on_the_same_fs);
// TODO: Write to the tmp file like normal here
// ...
// Use /proc/self/fd/ to get a file path for the unnamed temp file
let tmp_file_path = format!("/proc/self/fd/{}", file.as_raw_fd());
// Persist the temp file to a new named path
nix::unistd::linkat(
None,
&tmp_file_path[..],
None,
&file_path[..],
nix::unistd::LinkatFlags::SymlinkFollow,
)?;
```
=> Remove `O_EXCL` to allow for tmpfile persistence on Linux

src/dir.rs, src/file/mod.rs
- Reduce size of `TempDir` and `TempPath` by using `Box<Path>` instead of `PathBuf`, since neither `TempDir` nor `TempPath` uses any function specific to `PathBuf` rather than deallocating them.
For `TempDir::into_path` and `TempPath::into_path`, it is converted back into `PathBuf` with zero cost.
- Reduce size of `TempDir` by removing use of `Option` and uses `mem::forget` and `mem::ManuallyDrop` to avoid calling `Drop::drop`, and use set field `TempDir::path` to an empty `Box`: `PathBuf::new().into_boxed_path()` to deallocate the heap memory.
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>
=> Reduce size of TempDir and TempPath

src/spooled.rs
Heya! Really appreciate this library - using it for something and wound up with a case where I needed to extract the underlying storage on a `SpooledTempFile`.
In my case, once I've finished writing it, I need to pass it off to an async runtime to work with. Rather than deal with implementing `AsyncRead`/`AsyncWrite` on `SpooledTempFile`, I found it easier to simply pull out the underlying type and use the general `From`/`Into` conversion methods to get to an async file/cursor.
This effectively sidesteps dragging a bunch of async-related crates into this while still enabling a path towards bridging them. Something you'd be open to merging?
=> Expose `SpooledInner` and add a `into_inner()`.

Cargo.toml, src/util.rs
Re-opens #118.
At the time the PR was submitted, fastrand was new. But it's been a year now since we switched to
SmallRng and it's still going strong.
While this will _slightly_ increase the build size for crates already depending on rand, fastrand is
really small and has no direct dependencies.
Security: Neither Go nor Python's tempfile name generator use cryptographic randomness, so I'm feeling pretty comfortable sticking with non-cryptographic randomness here.
=> replace rand with fastrand

src/lib.rs
This commit adds a section to the `src/libs.rs` docs pointing out an easily encounterable error when ussing `tempdir()` with apis that are generic over `AsRef<Path>`, like `Command::current_dir`, resulting in the directory being dropped to early (As pointed out in #115).
replaces #116 with some fixups.
=> Add docs pointing out early dop pitfalls

Cargo.toml, NEWS, src/file/mod.rs, src/lib.rs, src/util.rs, tests/namedtempfile.rs
There are two main parts to this PR. Unfortunately GitHub doesn't really have the ability to make PRs depend on each other. Let me know if you want this split up into separate PRs.
Fixes #175
This adds a generic parameter to `NamedTempFile`. This enables using it with non-File types, such as:
- `std::os::unix::net::UnixListener`,
- `tokio::net::UnixListener`, or
- `tokio::fs::File`
This should be a backwards compatible change. To do this, some `File`-specific stuff is only implemented for `NamedTempFile<File>`.
This enables the user to leverage the file-path building part of the library while providing their own custom file creation callback. This is useful for creating UNIX domain sockets.
It was mentioned in #175 to provide a helper for creating sockets, but since UNIX domain sockets …
=> Add NamedTempFile<F>, Builder::{make,make_in}, and NamedTempFile::from_parts

src/dir.rs, src/lib.rs, src/spooled.rs
Based on encountering some code that called `TempDir::path` and ignored
the result.
=> Add `#[must_use]` to various functions

src/file/mod.rs, src/lib.rs
documentation notes static declared instances may leak (like with
lazy_static). Links to underlying reason
https://github.com/rust-lang-nursery/lazy-static.rs/issues/62
Issue #183
=> doc clarify statics may leak

.github/workflows/ci.yml, Cargo.toml, README.md, src/file/imp/unix.rs
This ports tempfile to use the rustix crate instead of making direct libc calls, which factors out an `unsafe` block, simplifies error handling, and simplifies string handling.
While here, it also implements a suggestion in a comment; on recent Linux it uses `renameat2` with `RENAME_NOREPLACE` to implement `persist` in non-overwrite mode.
This does require incrementing the minimum required Rust version to 1.48. Please feel free to decline this PR if you don't wish to take on these new requirements.
=> Port to rustix, and add support for using Linux's `renameat2`

.github/workflows/ci.yml
We currently test a _wasi_ build, but not bare wasm. We should at least compile with wasm.
=> ci: check wasm build

Cargo.toml
The main change in this version is to switch to using the I/O safety types and traits from std, on Rust versions where they're available.
=> Update to rustix 0.36.

src/util.rs
Previously when creating a temporary file without any random characters
in it, a loop would effectively run once and fail with the conclusion
that a file could not be created because too many temporary files exist
(2_147_483_648).
Now it will return the original failure, which typically is that the
file with the given name already existed.
This can more easily happen on case-insentiive file systems, and the
correct error message helps understanding what went wrong.
See https://github.com/Byron/gitoxide/issues/595 for reference.
=> fix: don't claim 'too many temporary files exist' if a file already existed, once.

Cargo.toml, src/dir.rs
=> Remove remove_dir_all dependency

src/lib.rs
This will be helpful for people migrating from tempdir
(TempDir::new_in), which accepts a prefix and a destination folder as
parameters.
Developers are suggested migrating to tempfile through RUSTSEC-2018-0017.
The example is quite simple, but it's especially helpful for people not
too familiar with Builders, which could be coming from tempdir which has a
method that accomplishes this.
Example of migration from tempdir to tempfile:
https://github.com/kinnison/git-testament/commit/1538fa0dfdd927bb93ac837031ab2cf3b5ec2b2e
=> Add Builder usage example for tempdir with a chosen prefix under a chosen folder

.github/workflows/ci.yml
Macos 1.48.0 is failing right now (https://github.com/rust-lang/rust/issues/107252).
=> ci: disable fail-fast

.github/workflows/ci.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/Stebalien/tempfile/actions/runs/4271041404:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/cargo` are replaced by direct invocations of `cargo`.
=> ci: replace unmaintained actions-rs/cargo actions in CI workflows

.github/workflows/ci.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/Stebalien/tempfile/actions/runs/4272369713:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).
=> ci: replace unmaintained actions-rs/toolchain action in CI workflows

.github/dependabot.yml
With this Dependabot will automatically file PRs to update dependencies. The cargo section watches `Cargo.toml` for semver-incompatible crate updates while the github-actions section watches the workflow files in `.github/workflows` for possible updates to any of the action in use.
=> Add a Dependabot config

src/file/imp/other.rs
These two are intentionally unused but are warned about when building e.g. wasm32-unknown-unknown.
=> Silence unused variable warnings

Cargo.toml
It's good to have the MSRV available in a standarized, machine readable format.
=> Specify the MSRV in the Cargo.toml

.github/workflows/ci.yml
- Downgrade to XCode 13 if the test runs with Rust 1.48 on macOS. Fixes the failing CI on that configuration.
- Add rustfmt and clippy to CI
- Add stable Rust to CI
- Two tiny style nits.
=> Fix and expand CI

src/file/mod.rs, tests/namedtempfile.rs
Due to bug rust-lang/rust#96634, these generic bounds may cause an infinite recursion in the compiler, even in unrelated code.
This specializes the `Write for &NamedTempFile<F>` impl on `File` instead. This keeps the API the same as before the generic parameter `F` was added in #177, so it shouldn't break any code. If/when the compiler bug is fixed, we can switch it back to the more generic version. Very few types implement `Write for &T`, however. The only other one I know of is `UnixStream`, which probably wouldn't be used with `NamedTempFile` anyway (it's counterpart `UnixListener` is used instead).
Fixes #224.
=> NamedTempFile: Fix infinite recursion in trait bounds

src/file/mod.rs
Instead of using the default method implementations, forward them to the underlying file. This allows the user to, e.g., take advantage of vectorized IO.
=> Forward default NamedTempFile methods

Cargo.toml
Reduces compile times. Technically, downstream users can do this themselves, but they likely won't know what's going on. This saves them the trouble.
fixes #228
=> chore: bump rustix min version to 0.37.11

Cargo.toml, build.rs, src/file/mod.rs
We don't implement the "into" variants as that'll drop and delete the temporary file.
=> feat: implement AsFd/AsHandle to mirror the AsRaw* variants

src/file/imp/windows.rs
The function cannot actually be used to move a file and set its attributes in one operation.
Fixes #234.
=> Remove comment on SetFileInformationByHandle

src/file/imp/unix.rs
Rustix on Haiku doesn't support `CWD`, so use the non-`at` versions of functions, since tempfile was only ever passing `CWD` to them.
For `link`, switch to `std::fs::hard_link`, since the `link` function has platform-dependent behavior and std has code to deal with that. This should also help portability to some platforms which lack `linkat`.
=> Use `rename`/`unlink`/`etc. instead of `renameat`/`unlinkat`/etc.

tests/tempdir.rs
We had some leftovers from when the tempdir crate was merged.
=> chore: cleanup tempdir tests

src/dir.rs, src/file/mod.rs, tests/namedtempfile.rs, tests/tempdir.rs
- `TempDir::with_prefix(prefix)`
- `TempDir::with_prefix_in(prefix, directory)`
- `TempFile::with_prefix(prefix)`
- `TempFile::with_prefix_in(prefix, directory)`
fixes #249
=> feat: add convenience methods for creating temp files with prefixes

.github/workflows/ci.yml, deny.toml
Add `cargo deny` configuration which matches status quo of the crate. Also add a job to CI to run the check.
This will cause CVEs, duplicate dependencies, unexpected licenses, and other issues to be caught during CI, before the crate is published.
=> Add cargo deny config and add cargo deny job to ci

src/file/mod.rs
The docstring for `NamedTempFile::new_in` appears to be wrong.
=> Correct docs about what this is equivalent to

Cargo.toml
Technically we don't need to patch this here, but this will fix any hidden bugs in downstream crates.
fixes #259
=> chore: update rustix to 0.38.21

Cargo.toml
This is the first update to the `windows-sys` crate in 8 months.  https://github.com/microsoft/windows-rs/releases/tag/0.52.0
=> Update `windows-sys` 0.52

src/dir/imp/any.rs, src/dir/imp/mod.rs, src/dir/imp/unix.rs, src/dir/mod.rs, src/file/imp/other.rs, src/file/imp/unix.rs, src/file/imp/windows.rs, src/file/mod.rs, src/lib.rs, src/util.rs
This PR allows the user to control the file mode set for newly created `NameTempfile` instances.
This is paramount for when tempfiles are used as scratch space that will be persisted and renamed into the final destination once all writes are completed. This is an effective way to prevent half-written files on disk and to assure that readers can only observe the final result of a change.
This paradigm is implemented in the `gix-lock` crate which is used by the `gix-ref` crate for editing Git references. Currently these are created with `0o600` permissions, which can cause [issues when using `sudo`](https://github.com/stacked-git/stgit/issues/413) in downstream applications.
When this PR is merged, `gix-ref` can be adjusted to allow setting the mode [just like Git …
=> feat: Add `Builder::permissions()` method.

src/spooled.rs, src/util.rs, tests/spooled.rs
Make sure that calculations do not overflow.
Also do not truncate u64 to usize on 32 bit systems.
I have added tests to showcase the issues.
=> Fix integer overflows and truncation

src/lib.rs
It has to end with version (or latest).
Fixes ecb73745c552f9df53f8943ea80e9bebf51643a2.
Just checked. Otherwise the links are broken. Sorry for the second push into the previous branch.
=> chore: fix doc url

CHANGELOG.md, Cargo.toml, src/dir/mod.rs, src/env.rs, src/file/imp/unix.rs, src/file/mod.rs, src/lib.rs, tests/namedtempfile.rs, tests/tempdir.rs
This adds a new `env` module with `override_temp_dir` and `temp_dir` functions.
- `temp_dir` will defer to `std::env::temp_dir` by default unless the temporary directory has been overridden.
- `override_temp_dir` allows the user to override the default temporary directory ONCE. Once this value has been set, it cannot be changed Care should be taken to ensure that the chosen directory is actually writable.
This API is designed for use by the application author when the application may run in an environment without a reliable global temporary directory (e.g., Android).
fixes #285
=> feat: add the ability to override the default temporary directory

src/dir/imp/any.rs, src/dir/imp/unix.rs, src/dir/mod.rs, src/file/imp/unix.rs, src/file/imp/windows.rs, src/file/mod.rs, src/lib.rs, src/util.rs, tests/namedtempfile.rs, tests/tempdir.rs
Fixes https://github.com/Stebalien/tempfile/issues/194
=> add keep() function to builder that suppresses delete-on-drop behavior

src/lib.rs
=> Document default permissions for tempdirs

src/dir/mod.rs, src/file/mod.rs, tests/namedtempfile.rs, tests/tempdir.rs
closes #298 
Adds a `with_suffix` to correspond to `with_prefix`. Allows for easier filetype specification and naming.
=> plumbing for `with_suffix` for issue #298

Cargo.toml
dependabot bumped the version to 0.59 but older version 0.52 can also be supported allowing downstream crates to pull dependency as per their version choice.
=> allow older windows-sys 0.52

.github/workflows/ci.yml, Cargo.toml, src/lib.rs
- wasip2 will require +nightly until https://github.com/rust-lang/rust/issues/130323 is resolved and/or std::os::wasip2 is available in stable.
- Support was added to rustix for version 0.38.39 https://github.com/bytecodealliance/rustix/pull/1205
=> fix: enable wasip2 feature for wasm32-wasip2 target

CHANGELOG.md
I clicked the link to learn from the ticket - and found it went to the wrong ticket.
=> Fix link to ticket in changelog

CHANGELOG.md, Cargo.toml, src/lib.rs, src/util.rs, tests/namedtempfile.rs
Re-seed thread-local RNG from system randomness if we run into a temporary file-name collision. This should address the concerns about using a predictable RNG without hurting performance in the common case where nobody is trying to predict our filenames. I'm only re-seeding once because if we _still_ fail to create a temporary file, the collision was likely due to too many temporary files instead of an attacker predicting our random temporary file names.
I've also reduced the number of tries from 2^31 to 2^16. If it takes more than that to create a temporary file, something else is wrong. Pausing for a long time is usually worse than just failing.
fixes #178
=> feat: re-seed from system randomness on collision

src/dir/mod.rs, src/env.rs, src/lib.rs
Alternative to #311 (this patch includes a few miscellaneous documentation fixes from that PR as well).
The previous documentation didn't sufficiently cover permissions issues and mixed all the security concerns into a single section. This patch separates things out into separate sections and hopefully makes all this easier to understand.
This patch also documents the DoS mitigation introduced in #314 (I stared writing this documentation first then decided that I'd rather just fix the DoS vector...).
I've also removed the link to the OWASP documentation to avoid confusing users (their documentation is mostly concerned with low-level C and platform-specific temporary file creation functions).
=> docs: improve & expand security documentation

Cargo.toml, src/util.rs
This upgrades to `getrandom` v0.3, which was released today.
Changelog: https://github.com/rust-random/getrandom/blob/master/CHANGELOG.md#030---2025-01-25
It may make sense to wait a bit before releasing this upgrade as the rest of the ecosystem (including `rand`) hasn't upgraded yet.
=> build: upgrade getrandom to v0.3.0

src/file/mod.rs, src/lib.rs, src/util.rs, tests/namedtempfile.rs
We used absolute paths in the builder when making directories and in `create_named` but this didn't cover `Builder::make_in` and technically introduced a small race in some unnamed tempfile cases (i.e., when we can't atomically create unnamed temporary files and need to create then immediately delete them).
Instead, we now resolve the filename into an absolute path inside the main create helper.
=> fix: always use absolute paths

src/util.rs, tests/namedtempfile.rs
Previously, creating a temporary file from a TLS destructor could panic in fastrand (because the thread-local RNG may have been deallocated).
Now, we fork the RNG before we create each file, falling back on an RNG with a static seed if the thread-local RNG has been deallocated.
Two downsides to this patch:
1. Temporary files created during TLS deallocation will have extremely predictable names until the `getrandom` re-seed kicks in (assuming that feature is enabled). IMO, that's fine; this would panic previously.
2. `getrandom` re-seeding used to re-randomize to the entire per-thread RNG, now it only applies to the per-filename RNG. However, the will still serve its purpose as a mitigation against potential DoS attacks.
I also considered managing the thread-local RNG myself instead of …
=> fix: handle TLS deallocation

src/util.rs
New in getrandom 0.3, we can now get numbers directly. On some systems, this'll use special CPU instructions and can be instantaneous. We're not using them for crypto, so I'm not going to be picky.
=> feat: simplify getrandom call

src/file/mod.rs
=> doc: clarify "inner file will be deleted" documentation

src/file/imp/windows.rs
This isn't necessary for windows-sys 0.59, but is for windows-sys 0.52.
fixes #331
=> fix: cast handle to the windows crate HANDLE

Cargo.toml, src/file/imp/mod.rs, src/file/imp/unix.rs
It's tiny, but we don't really need it so we might as well trim our dependencies down a bit.
=> chore: remove cfg-if dependency

.github/workflows/ci.yml
I'm doing this in CI instead of in the Cargo.toml file because I don't want to force users of newer rustc versions to use old versions of `once_cell`. Ironically, I only depend on `once_cell` to support ancient rust versions in the first place.
=> ci: downgrade once-cell on old rustc versions

Cargo.toml, src/file/imp/windows.rs
This adds a feature making it possible to disable the immediate deletion of unnamed temporary files on windows (introduced in 461369fd). Hopefully, this will fix #339. If so, I'll revert 461369fd entirely.
=> feat(windows): add a feature to immediate tempfile deletion

CHANGELOG.md, Cargo.toml, src/file/imp/windows.rs
We tried doing this to match the behavior on Unix platforms but this appears to trigger some form of Windows kernel bug at scale. Given that it's not necessary, we're reverting it. I'm leaving the feature flag in the `Cargo.toml` for now but will remove it in the near future.
fixes #339
=> fix(windows): don't automatically delete files on open

.github/workflows/ci.yml, tests/env.rs, tests/namedtempfile.rs, tests/spooled.rs, tests/tempdir.rs, tests/tempfile.rs
fixes #326 
Actually running the tests is straightforward (well, we've figured this out before in zlib-rs), but most tests fail because the `std::env::temp_dir()` function panics for the wasi platforms (see https://github.com/rust-lang/rust/blob/master/library/std/src/sys/pal/wasi/os.rs#L267).
So, I'm using `override_temp_dir` in combination with the `--dir "/tmp"` argument to wasmtime to make the tests pass. That's a bit annoying, but the best I could come up with. There are also some tests that are ignored now for the wasi targets because e.g. they spawn threads and that is just not supported.
=> run `wasm32-wasip1` and `wasm32-wasip2` tests on CI

.github/workflows/ci.yml
This is what most people will be using at this point, and this is the target machine architecture anyways.
=> ci: test macos on aarch64 instead of x86

src/dir/mod.rs, src/lib.rs, tests/tempdir.rs
This unifies the `TempDir`/`NamedTempFile` method names to help avoid confusion.
=> feat: rename `TempDir::into_path` to `TempDir::keep`

src/dir/mod.rs
Mistakenly excluded from the previous PR.
=> fix: add must_use attribute to TempDir::keep

src/dir/imp/any.rs, src/dir/imp/unix.rs, src/dir/mod.rs, src/file/mod.rs, src/lib.rs, tests/namedtempfile.rs, tests/tempdir.rs
This makes it possible to disable automatic cleanup of temporary files & directories _after_ they've been created.
1. Rename `Builder::keep` into `Builder::disable_cleanup` for consistency. `::keep` on `NamedTempDir`, `TempDir`, `TempPath`, etc. provide a way to _convert_ (one-way) a temporary directory/file into a persistent temporary directory/file but aren't a way to simply disable automatic cleanup in-place.
2. Add `disable_cleanup` methods to all named temporary file types, making it possible to replicate the behavior of `Builder::disable_cleanup` _after_ creating a temporary file. Given that this operation is in-place, it can be undone.
fixes #347
=> feat: make it possible to disable cleanup in-place after creation

src/lib.rs
=> doc(builder): clarify permissions

src/lib.rs
1. Remove an extra backtick which breaks the markdown formatting:
2. Nit, don't feel strongly: use a semicolon between two independent clauses, instead of a comma. Adding "since" after the comma would work too.
=> Fix formatting in `Builder::disable_cleanup` documentation
