Stebalien/tempfile

src/lib.rs
=> Expose PersistError

src/file/mod.rs, src/lib.rs, tests/namedtempfile.rs
Fixes #36.
I've tested this with my project that is using tempfile and it works as expected.
I will refactor after #33 is merged.
=> Allow closing of a NamedTempFile file handle

src/dir.rs
fixes #42 
This just fixes the docs. We should discuss more if the function name should change as well
=> improve docs for TempDir::into_path

Cargo.toml
This will also bump the minimum winapi version to 0.3
=> Bump remove_dir_all version to 0.5

Cargo.toml, rustfmt.toml, src/dir.rs, src/file/imp/unix.rs, src/file/imp/windows.rs, src/file/mod.rs, src/lib.rs, src/util.rs, tests/namedtempfile.rs, tests/tempdir.rs, tests/tempfile.rs
=> modernize code

.travis.yml, README.md, appveyor.yml, src/dir.rs, src/error.rs, src/file/mod.rs, src/lib.rs, src/spooled.rs, src/util.rs, tests/spooled.rs, tests/tempdir.rs, tests/tempfile.rs
(so my editor doesn't make random changes in every file I touch)
=> chore: format

src/file/imp/unix.rs, src/file/imp/windows.rs
=> use modern stdlib features

src/file/mod.rs, tests/namedtempfile.rs
=> Add NamedTempFile::into_parts

src/file/imp/other.rs, src/file/imp/unix.rs, src/file/imp/windows.rs, src/file/mod.rs, tests/namedtempfile.rs
=> implement TempPath::keep

src/lib.rs, src/spooled.rs, src/util.rs
* lint with clippy
* replace call to write with a call to write_all
* export PathPersistError (fixes #25)
=> misc bug fixes

src/file/imp/other.rs, src/file/imp/unix.rs, src/file/imp/windows.rs, src/file/mod.rs, src/lib.rs, tests/namedtempfile.rs
=> Add an append flag to Builder

src/lib.rs
=> doc: add an example for re-opening named temporary files

Cargo.toml, README.md, src/dir.rs, src/error.rs, src/file/imp/unix.rs, src/file/imp/windows.rs, src/file/mod.rs, src/lib.rs, src/spooled.rs, src/util.rs, tests/namedtempfile.rs, tests/spooled.rs, tests/tempdir.rs, tests/tempfile.rs
=> Transit to 2018 edition

src/file/mod.rs
Hello!
This is just a super small change to the docs.  
It looks like in 2 places "if" was typo'd as "iff."
=> Change "iff" to "if" and remove apostrophe from "it's"

.travis.yml, README.md, appveyor.yml
Required by remove-dir-all.
fixes #120
=> bump msrv to 1.40.0

Cargo.toml, src/lib.rs
This provide a simple way to check that your README example is up-to-date.
=> Ensure that README code example is up to date

Cargo.toml
=> Fix the build on Redox with -Zminimal-versions

Cargo.toml, src/file/imp/windows.rs, src/spooled.rs
`winapi` has been replaced by `windows-sys`.
=> Use official `windows-sys` bindings

src/dir.rs
=> doc: fix tempdir_in documentation

NEWS
This pull request fixes a typo.
=> Fix a typo in NEWS

src/spooled.rs
That way we can take advantage of, e.g., vectorized operations.
=> feat: implement default methods for SpooledTempFile Read/Write

Cargo.toml, src/file/imp/unix.rs
=> fix: drop redox_syscall dependency

Cargo.toml
Nothing to change here, just an edition bump.
=> chore: 2021 edition

src/dir/mod.rs, src/file/mod.rs, src/lib.rs, src/spooled.rs
We no longer need wrapping "main" blocks.
=> chore: modernize doctests

src/lib.rs
=> fix: expose SpooledData enum

src/file/mod.rs
=> doc: document atomicity of `persist_noclobber`

src/spooled.rs
This makes it possible to convert a spooled temporary file into a regular temporary file.
=> feat: implement `SpooledTempFile::into_file`
